spring.application.name=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=

hashids.secret=
#spring.jpa.properties.hibernate.connection.url=${spring.datasource.url}
#spring.jpa.properties.hibernate.connection.autocommit
#spring.jpa.properties.hibernate.connection.isolation
#spring.jpa.properties.hibernate.connection.pool_size
